defaultTimezone: UTC

useNamedEntityForAuthorExtraction: true

# AirPR Extractor Configuration
#extractorBaseUrl: http://extractor.airpr.com/api/
extractorBaseUrl: http://localhost:8080/api/
extractorEntityPath: entities
extractorUserName: extractor
extractorPassword: Hc7kvADwxxsJFvKCtqnm6byWaNRgUrzd

nerExclusion:
  - Destiny Bertucci

bestElementForAuthor:
  reuters.com: ':containsOwn(reporting by), :containsOwn(reported by), :containsOwn(edited by), :containsOwn(editing by)'
  upi.com: '#px > div.c_p > div.meta.grey'

  # Need to fix
  marketingprofs.com: 'span[itemprop=author]'
  foxnews.com: 'div.meta > div > span > a'
  ge.com: 'div > hgroup > h4 > a'
  globalbankingandfinance.com: 'div.the-content.post-content.clearfix > p:nth-child(1) > strong > em'
  apnews.com: '#contentArea > div:nth-child(2) > div:nth-child(1) > h6'
  bloomberg.com: 'body > main > div > article > div.lede-text-only.lede > div.lede-text-only__container > div > address'
  computerpartner.at: 'meta[name=Author]'
  cioreview.com: '#namepost > font'

  # Not working - Blank Domain
  jdsupra.com: '#followPeopleSection > div.follow-people-list.f6.lh-title > div > div > div:nth-child(2) > a'
  einnews.com: 'p:contains(Media Contact)'
  adweek.com: 'span[itemprop=author]'

  # Fix this sequence
  nt4admins.de: 'dl > dd'





